---

- hosts: all
  user: root
  serial: 1
  tasks:
   - name: apt update
     raw: apt update
     changed_when: false

   - name: apt upgrade
     raw: DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -y
     register: upgrade_result
     changed_when: "'packages will be upgraded' in upgrade_result.stdout"

   - name: reboot
     reboot:
     when: upgrade_result.changed

   - name: apt autoremove --purge
     raw: apt autoremove --purge -y
